# Generated by Django 4.2 on 2023-04-17 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeployKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=1023)),
                ('public_path', models.CharField(max_length=255)),
                ('private_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('framework', models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI'), ('express', 'Express'), ('react', 'React'), ('svelte', 'Svelte'), ('django-react', 'Django + React'), ('django-svelte', 'Django + Svelte')], max_length=50)),
                ('git_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('certificate', models.DateField(blank=True, null=True)),
                ('cert_mail', models.EmailField(default='mahmudula2000@gmail.com', max_length=254)),
                ('domain', models.URLField(blank=True, null=True)),
                ('deploy_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy.deploykey')),
                ('environments', models.ManyToManyField(blank=True, to='deploy.environment')),
                ('extra_commands', models.ManyToManyField(blank=True, to='deploy.command')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField()),
                ('deploy_time', models.DateTimeField(auto_now_add=True)),
                ('logs', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.website')),
            ],
            options={
                'ordering': ('-deploy_time',),
            },
        ),
    ]
