# Generated by Django 4.2 on 2023-05-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_remove_website_extra_commands_remove_website_git_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
