# Generated by Django 4.2 on 2023-05-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_alter_deploy_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='framework',
            field=models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI'), ('express', 'Express'), ('react', 'React'), ('svelte', 'Svelte'), ('static', 'Static'), ('django-react', 'Django-React'), ('django-svelte', 'Django-Svelte')], max_length=50),
        ),
    ]
